const colleges = [
{ id: 1,college: "Adelphi University" },
{ id: 2,college: "Agnes Scott College" },
{ id: 3,college: "Alabama A&M" },
{ id: 4,college: "Allegheny College" },
{ id: 5,college: "American International College" },
{ id: 6,college: "American University" },
{ id: 7,college: "Amherst College" },
{ id: 8,college: "Andrews University" },
{ id: 9,college: "Appalachian State University" },
{ id: 10,college: "Arizona State University - Tempe" },
{ id: 11,college: "Art Center College of Design" },
{ id: 12,college: "Ashland University" },
{ id: 13,college: "Auburn University" },
{ id: 14,college: "Augusta University" },
{ id: 15,college: "Augustana College" },
{ id: 16,college: "Augustana University" },
{ id: 17,college: "Austin College" },
{ id: 18,college: "Azusa Pacific University" },
{ id: 19,college: "Ball State University" },
{ id: 20,college: "Bard College" },
{ id: 21,college: "Barnard College" },
{ id: 22,college: "Barry University" },
{ id: 23,college: "Bates College" },
{ id: 24,college: "Baylor University" },
{ id: 25,college: "Bellarmine University" },
{ id: 26,college: "Belmont Abbey College" },
{ id: 27,college: "Belmont University" },
{ id: 28,college: "Beloit College" },
{ id: 58,college: "Carleton College" },
{ id: 29,college: "Benedictine University" },
{ id: 30,college: "Bennett College" },
{ id: 31,college: "Bennington College" },
{ id: 32,college: "Bentley University" },
{ id: 33,college: "Berry College" },
{ id: 34,college: "Biola University" },
{ id: 35,college: "Blue Mountain College" },
{ id: 36,college: "Boise State University" },
{ id: 37,college: "Boston College" },
{ id: 38,college: "Boston University" },
{ id: 39,college: "Bowdoin College" },
{ id: 40,college: "Bowling Green State University" },
{ id: 41,college: "Bradley University" },
{ id: 42,college: "Brandeis University" },
{ id: 43,college: "Brigham Young University - Provo" },
{ id: 44,college: "Brown University" },
{ id: 45,college: "Bryant University" },
{ id: 46,college: "Bryn Mawr College" },
{ id: 47,college: "Bucknell University" },
{ id: 48,college: "Butler University" },
{ id: 49,college: "CUNY - Baruch College" },
{ id: 50,college: "California Institute of Technology" },
{ id: 51,college: "California Institute of the Arts" },
{ id: 52,college: "California Polytechnic State University - San Luis Obispo" },
{ id: 53,college: "California State Polytechnic University - Pomona" },
{ id: 54,college: "California State University - Fresno" },
{ id: 55,college: "California State University - Fullerton" },
{ id: 56,college: "Calvin College" },
{ id: 57,college: "Cardinal Stritch University" },
{ id: 59,college: "Carnegie Mellon University" },
{ id: 60,college: "Carroll College" },
{ id: 61,college: "Case Western Reserve University" },
{ id: 62,college: "Catawba College" },
{ id: 63,college: "Catholic University of America" },
{ id: 64,college: "Cazenovia College" },
{ id: 65,college: "Cedar Crest College" },
{ id: 66,college: "Central Michigan University" },
{ id: 67,college: "Centre College" },
{ id: 68,college: "Chapman University" },
{ id: 69,college: "City College of New York" },
{ id: 70,college: "Claflin University" },
{ id: 71,college: "Claremont McKenna College" },
{ id: 72,college: "Clark Atlanta University" },
{ id: 73,college: "Clark University" },
{ id: 74,college: "Clarkson University" },
{ id: 75,college: "Clemson University" },
{ id: 76,college: "Cleveland State University" },
{ id: 77,college: "Coe College" },
{ id: 78,college: "Coker College" },
{ id: 79,college: "Colby College" },
{ id: 80,college: "Colgate University" },
{ id: 81,college: "College of Charleston" },
{ id: 82,college: "College of New Jersey" },
{ id: 83,college: "College of St. Benedict" },
{ id: 84,college: "College of William & Mary" },
{ id: 85,college: "College of Wooster" },
{ id: 86,college: "College of the Atlantic" },
{ id: 87,college: "College of the Holy Cross" },
{ id: 117,college: "Edgewood College" },
{ id: 88,college: "College of the Ozarks" },
{ id: 89,college: "Colorado College" },
{ id: 90,college: "Colorado School of Mines" },
{ id: 91,college: "Colorado State University" },
{ id: 92,college: "Columbia University" },
{ id: 93,college: "Concordia College - Moorhead" },
{ id: 94,college: "Connecticut College" },
{ id: 95,college: "Cooper Union" },
{ id: 96,college: "Cornell College" },
{ id: 97,college: "Cornell University" },
{ id: 98,college: "Creighton University" },
{ id: 99,college: "Dallas Baptist University" },
{ id: 100,college: "Dartmouth College" },
{ id: 101,college: "Davidson College" },
{ id: 102,college: "DePaul University" },
{ id: 103,college: "DePauw University" },
{ id: 104,college: "Denison University" },
{ id: 105,college: "Dickinson College" },
{ id: 106,college: "Dillard University" },
{ id: 107,college: "Dordt College" },
{ id: 108,college: "Drake University" },
{ id: 109,college: "Drew University" },
{ id: 110,college: "Drexel University" },
{ id: 111,college: "Duke University" },
{ id: 112,college: "Duquesne University" },
{ id: 113,college: "Earlham College" },
{ id: 114,college: "East Carolina University" },
{ id: 115,college: "East Tennessee State University" },
{ id: 116,college: "Eastern Michigan University" },
{ id: 118,college: "Elizabethtown College" },
{ id: 119,college: "Elmhurst College" },
{ id: 120,college: "Elon University" },
{ id: 121,college: "Embry-Riddle Aeronautical University" },
{ id: 122,college: "Emerson College" },
{ id: 123,college: "Emory University" },
{ id: 124,college: "Fairfield University" },
{ id: 125,college: "Fayetteville State University" },
{ id: 126,college: "Fisk University" },
{ id: 127,college: "Flagler College" },
{ id: 128,college: "Florida A&M University" },
{ id: 129,college: "Florida Atlantic University" },
{ id: 130,college: "Florida Institute of Technology" },
{ id: 131,college: "Florida International University" },
{ id: 132,college: "Florida State University" },
{ id: 133,college: "Fordham University" },
{ id: 134,college: "Franklin W. Olin College of Engineering" },
{ id: 135,college: "Franklin and Marshall College" },
{ id: 136,college: "Furman University" },
{ id: 137,college: "Gallaudet University" },
{ id: 138,college: "Gardner-Webb University" },
{ id: 139,college: "George Mason University" },
{ id: 140,college: "George Washington University" },
{ id: 141,college: "Georgetown University" },
{ id: 142,college: "Georgia Institute of Technology" },
{ id: 143,college: "Georgia Southern University" },
{ id: 144,college: "Georgia State University" },
{ id: 145,college: "Gettysburg College" },
{ id: 146,college: "Gonzaga University" },
{ id: 147,college: "Goshen College" },
{ id: 148,college: "Goucher College" },
{ id: 149,college: "Grand Canyon University" },
{ id: 150,college: "Grinnell College" },
{ id: 151,college: "Gustavus Adolphus College" },
{ id: 152,college: "Hamilton College" },
{ id: 153,college: "Hampden-Sydney College" },
{ id: 154,college: "Hampton University" },
{ id: 155,college: "Harvard University" },
{ id: 156,college: "Harvey Mudd College" },
{ id: 157,college: "Haverford College" },
{ id: 159,college: "Hendrix College" },
{ id: 160,college: "High Point University" },
{ id: 161,college: "Hillsdale College" },
{ id: 162,college: "Hobart and William Smith Colleges" },
{ id: 163,college: "Hofstra University" },
{ id: 164,college: "Hollins University" },
{ id: 165,college: "Hope College" },
{ id: 166,college: "Howard Payne University" },
{ id: 167,college: "Howard University" },
{ id: 168,college: "Huntingdon College" },
{ id: 169,college: "Illinois Institute of Technology" },
{ id: 170,college: "Illinois State University" },
{ id: 171,college: "Illinois Wesleyan University" },
{ id: 172,college: "Immaculata University" },
{ id: 173,college: "Indiana State University" },
{ id: 174,college: "Indiana University - Bloomington" },
{ id: 175,college: "Indiana University of Pennsylvania" },
{ id: 176,college: "Indiana University-Purdue University - Indianapolis" },
{ id: 177,college: "Iowa State University" },
{ id: 178,college: "Ithaca College" },
{ id: 179,college: "Jackson State University" },
{ id: 180,college: "James Madison University" },
{ id: 181,college: "John Carroll University" },
{ id: 182,college: "Johns Hopkins University" },
{ id: 183,college: "Juniata College" },
{ id: 184,college: "Kalamazoo College" },
{ id: 185,college: "Kansas State University" },
{ id: 186,college: "Kennesaw State University" },
{ id: 187,college: "Kent State University" },
{ id: 188,college: "Kenyon College" },
{ id: 189,college: "Kettering University" },
{ id: 190,college: "Knox College" },
{ id: 191,college: "Lafayette College" },
{ id: 192,college: "Lake Forest College" },
{ id: 193,college: "Lamar University" },
{ id: 194,college: "Lawrence University" },
{ id: 195,college: "Le Moyne College" },
{ id: 196,college: "Lehigh University" },
{ id: 197,college: "Lesley University" },
{ id: 198,college: "Lewis & Clark College" },
{ id: 199,college: "Liberty University" },
{ id: 200,college: "Lincoln University" },
{ id: 201,college: "Lindenwood University" },
{ id: 202,college: "Lipscomb University" },
{ id: 203,college: "Louisiana State University - Baton Rouge" },
{ id: 204,college: "Louisiana Tech University" },
{ id: 205,college: "Loyola Marymount University" },
{ id: 206,college: "Loyola University Chicago" },
{ id: 207,college: "Loyola University Maryland" },
{ id: 208,college: "Loyola University New Orleans" },
{ id: 209,college: "Luther College" },
{ id: 210,college: "Macalester College" },
{ id: 211,college: "Maine Maritime Academy" },
{ id: 212,college: "Manhattan College" },
{ id: 213,college: "Marietta College" },
{ id: 214,college: "Marist College" },
{ id: 215,college: "Marquette University" },
{ id: 216,college: "Maryville University of St. Louis" },
{ id: 217,college: "Massachusetts Institute of Technology" },
{ id: 218,college: "Massachusetts Maritime Academy" },
{ id: 219,college: "Mercer University" },
{ id: 220,college: "Messiah College" },
{ id: 221,college: "Miami University - Oxford" },
{ id: 222,college: "Michigan State University" },
{ id: 223,college: "Michigan Technological University" },
{ id: 224,college: "Middle Tennessee State University" },
{ id: 225,college: "Middlebury College" },
{ id: 226,college: "Mills College" },
{ id: 227,college: "Millsaps College" },
{ id: 228,college: "Milwaukee School of Engineering" },
{ id: 229,college: "Mississippi State University" },
{ id: 230,college: "Missouri University of Science & Technology" },
{ id: 231,college: "Montana State University" },
{ id: 232,college: "Montana Tech of the University of Montana" },
{ id: 233,college: "Montclair State University" },
{ id: 234,college: "Morehouse College" },
{ id: 235,college: "Morgan State University" },
{ id: 236,college: "Mount Holyoke College" },
{ id: 237,college: "Muhlenberg College" },
{ id: 238,college: "National Louis University" },
{ id: 239,college: "New College of Florida" },
{ id: 240,college: "New Jersey Institute of Technology" },
{ id: 241,college: "New Mexico State University" },
{ id: 242,college: "New School" },
{ id: 243,college: "New York University" },
{ id: 244,college: "North Carolina A&T State University" },
{ id: 245,college: "North Carolina Central University" },
{ id: 246,college: "North Carolina State University - Raleigh" },
{ id: 247,college: "North Dakota State University" },
{ id: 248,college: "Northcentral University" },
{ id: 249,college: "Northeastern University" },
{ id: 250,college: "Northern Arizona University" },
{ id: 251,college: "Northern Illinois University" },
{ id: 252,college: "Northwestern College" },
{ id: 253,college: "Northwestern University" },
{ id: 254,college: "Nova Southeastern University" },
{ id: 255,college: "Oakland University" },
{ id: 256,college: "Oberlin College" },
{ id: 257,college: "Occidental College" },
{ id: 258,college: "Ohio Northern University" },
{ id: 259,college: "Ohio State University" },
{ id: 260,college: "Ohio University" },
{ id: 261,college: "Ohio Wesleyan University" },
{ id: 262,college: "Oklahoma Baptist University" },
{ id: 263,college: "Oklahoma State University" },
{ id: 264,college: "Old Dominion University" },
{ id: 265,college: "Oregon Institute of Technology" },
{ id: 266,college: "Oregon State University" },
{ id: 267,college: "Pace University" },
{ id: 268,college: "Pennsylvania State University - University Park" },
{ id: 269,college: "Pepperdine University" },
{ id: 270,college: "Pitzer College" },
{ id: 271,college: "Pomona College" },
{ id: 272,college: "Portland State University" },
{ id: 273,college: "Prairie View A&M University" },
{ id: 274,college: "Pratt Institute" },
{ id: 275,college: "Presbyterian College" },
{ id: 276,college: "Princeton University" },
{ id: 277,college: "Principia College" },
{ id: 278,college: "Providence College" },
{ id: 279,college: "Purdue University" },
{ id: 280,college: "Quinnipiac University" },
{ id: 281,college: "Reed College" },
{ id: 282,college: "Regent University" },
{ id: 283,college: "Rensselaer Polytechnic Institute" },
{ id: 284,college: "Rhode Island School of Design" },
{ id: 285,college: "Rhodes College" },
{ id: 286,college: "Rice University" },
{ id: 287,college: "Ripon College" },
{ id: 288,college: "Robert Morris University" },
{ id: 289,college: "Rochester Institute of Technology" },
{ id: 290,college: "Rocky Mountain College" },
{ id: 291,college: "Rollins College" },
{ id: 292,college: "Rose-Hulman Institute of Technology" },
{ id: 293,college: "Rutgers University - New Brunswick" },
{ id: 294,college: "Rutgers University - Newark" },
{ id: 295,college: "SUNY - Binghamton University" },
{ id: 296,college: "SUNY - College of Environmental Science and Forestry" },
{ id: 297,college: "SUNY - Geneseo" },
{ id: 298,college: "SUNY - Polytechnic Institute" },
{ id: 299,college: "SUNY - Stony Brook University" },
{ id: 300,college: "SUNY - University at Albany" },
{ id: 301,college: "SUNY - University at Buffalo" },
{ id: 302,college: "Saint Louis University" },
{ id: 303,college: "Sam Houston State University" },
{ id: 304,college: "Samford University" },
{ id: 305,college: "San Diego State University" },
{ id: 306,college: "San Francisco State University" },
{ id: 307,college: "San Jose State University" },
{ id: 308,college: "Santa Clara University" },
{ id: 309,college: "Sarah Lawrence College" },
{ id: 310,college: "Savannah College of Art and Design" },
{ id: 311,college: "School of the Art Institute of Chicago" },
{ id: 312,college: "Scripps College" },
{ id: 313,college: "Seattle Pacific University" },
{ id: 314,college: "Seattle University" },
{ id: 315,college: "Seton Hall University" },
{ id: 316,college: "Sewanee: The University of the South" },
{ id: 317,college: "Shenandoah University" },
{ id: 318,college: "Simmons College" },
{ id: 319,college: "Skidmore College" },
{ id: 320,college: "Smith College" },
{ id: 321,college: "Soka University of America" },
{ id: 322,college: "South Dakota State University" },
{ id: 323,college: "Southern Illinois University - Carbondale" },
{ id: 324,college: "Southern Methodist University" },
{ id: 325,college: "Southwestern University" },
{ id: 326,college: "Spalding University" },
{ id: 327,college: "Spelman College" },
{ id: 328,college: "St. Anselm College" },
{ id: 329,college: "St. Francis College" },
{ id: 330,college: "St. John Fisher College" },
{ id: 331,college: "St. John's College - Annapolis" },
{ id: 332,college: "St. John's College - Santa Fe" },
{ id: 333,college: "St. John's University" },
{ id: 334,college: "St. Joseph's University" },
{ id: 335,college: "St. Lawrence University" },
{ id: 336,college: "St. Mary's College" },
{ id: 337,college: "St. Mary's College of California" },
{ id: 338,college: "St. Mary's College of Maryland" },
{ id: 339,college: "St. Michael's College" },
{ id: 340,college: "St. Olaf College" },
{ id: 341,college: "Stanford University" },
{ id: 342,college: "Stetson University" },
{ id: 343,college: "Stevens Institute of Technology" },
{ id: 344,college: "Stonehill College" },
{ id: 345,college: "Suffolk University" },
{ id: 346,college: "Swarthmore College" },
{ id: 347,college: "Syracuse University" },
{ id: 348,college: "Taylor University" },
{ id: 349,college: "Temple University" },
{ id: 350,college: "Tennessee State University" },
{ id: 351,college: "Tennessee Technological University" },
{ id: 352,college: "Texas A&M University - College Station" },
{ id: 353,college: "Texas A&M University - Commerce" },
{ id: 354,college: "Texas A&M University - Corpus Christi" },
{ id: 355,college: "Texas A&M University - Kingsville" },
{ id: 356,college: "Texas Christian University" },
{ id: 357,college: "Texas Lutheran University" },
{ id: 358,college: "Texas Southern University" },
{ id: 359,college: "Texas State University" },
{ id: 360,college: "Texas Tech University" },
{ id: 361,college: "Texas Woman's University" },
{ id: 362,college: "The Citadel" },
{ id: 363,college: "Thomas Aquinas College" },
{ id: 364,college: "Tougaloo College" },
{ id: 365,college: "Transylvania University" },
{ id: 366,college: "Trevecca Nazarene University" },
{ id: 367,college: "Trinity College" },
{ id: 368,college: "Trinity International University" },
{ id: 369,college: "Trinity University" },
{ id: 370,college: "Truman State University" },
{ id: 371,college: "Tufts University" },
{ id: 372,college: "Tulane University" },
{ id: 373,college: "Tuskegee University" },
{ id: 374,college: "Union College" },
{ id: 375,college: "Union University" },
{ id: 376,college: "United States Air Force Academy" },
{ id: 377,college: "United States Coast Guard Academy" },
{ id: 378,college: "United States Merchant Marine Academy" },
{ id: 379,college: "United States Military Academy" },
{ id: 380,college: "United States Naval Academy" },
{ id: 381,college: "University of Akron" },
{ id: 382,college: "University of Alabama" },
{ id: 383,college: "University of Alabama - Birmingham" },
{ id: 384,college: "University of Alabama - Huntsville" },
{ id: 385,college: "University of Alaska - Fairbanks" },
{ id: 386,college: "University of Arizona" },
{ id: 387,college: "University of Arkansas" },
{ id: 388,college: "University of Arkansas - Little Rock" },
{ id: 389,college: "University of California - Berkeley" },
{ id: 390,college: "University of California - Davis" },
{ id: 391,college: "University of California - Irvine" },
{ id: 392,college: "University of California - Los Angeles" },
{ id: 393,college: "University of California - Merced" },
{ id: 394,college: "University of California - Riverside" },
{ id: 395,college: "University of California - San Diego" },
{ id: 396,college: "University of California - Santa Barbara" },
{ id: 397,college: "University of California - Santa Cruz" },
{ id: 398,college: "University of Central Florida" },
{ id: 399,college: "University of Chicago" },
{ id: 400,college: "University of Cincinnati" },
{ id: 401,college: "University of Colorado - Boulder" },
{ id: 402,college: "University of Colorado - Denver" },
{ id: 403,college: "University of Connecticut" },
{ id: 404,college: "University of Dayton" },
{ id: 405,college: "University of Delaware" },
{ id: 406,college: "University of Denver" },
{ id: 407,college: "University of Evansville" },
{ id: 408,college: "University of Florida" },
{ id: 409,college: "University of Georgia" },
{ id: 410,college: "University of Hartford" },
{ id: 411,college: "University of Hawaii - Manoa" },
{ id: 412,college: "University of Houston" },
{ id: 413,college: "University of Idaho" },
{ id: 414,college: "University of Illinois - Chicago" },
{ id: 415,college: "University of Illinois - Urbana-Champaign" },
{ id: 416,college: "University of Iowa" },
{ id: 417,college: "University of Kansas" },
{ id: 418,college: "University of Kentucky" },
{ id: 419,college: "University of La Verne" },
{ id: 420,college: "University of Louisiana - Lafayette" },
{ id: 421,college: "University of Louisiana - Monroe" },
{ id: 422,college: "University of Louisville" },
{ id: 423,college: "University of Maine" },
{ id: 424,college: "University of Maine - Farmington" },
{ id: 425,college: "University of Maryland - Baltimore County" },
{ id: 426,college: "University of Maryland - College Park" },
{ id: 427,college: "University of Maryland - Eastern Shore" },
{ id: 428,college: "University of Massachusetts - Amherst" },
{ id: 429,college: "University of Massachusetts - Boston" },
{ id: 430,college: "University of Massachusetts - Dartmouth" },
{ id: 431,college: "University of Massachusetts - Lowell" },
{ id: 432,college: "University of Memphis" },
{ id: 433,college: "University of Miami" },
{ id: 434,college: "University of Michigan - Ann Arbor" },
{ id: 435,college: "University of Minnesota - Twin Cities" },
{ id: 436,college: "University of Mississippi" },
{ id: 437,college: "University of Missouri" },
{ id: 438,college: "University of Missouri - Kansas City" },
{ id: 439,college: "University of Missouri - St. Louis" },
{ id: 440,college: "University of Mobile" },
{ id: 441,college: "University of Montana" },
{ id: 442,college: "University of Montana - Western" },
{ id: 443,college: "University of Mount Union" },
{ id: 444,college: "University of Nebraska - Lincoln" },
{ id: 445,college: "University of Nebraska - Omaha" },
{ id: 446,college: "University of Nevada - Las Vegas" },
{ id: 447,college: "University of Nevada - Reno" },
{ id: 448,college: "University of New Hampshire" },
{ id: 449,college: "University of New Mexico" },
{ id: 450,college: "University of New Orleans" },
{ id: 451,college: "University of North Carolina - Chapel Hill" },
{ id: 452,college: "University of North Carolina - Charlotte" },
{ id: 453,college: "University of North Carolina - Greensboro" },
{ id: 454,college: "University of North Dakota" },
{ id: 455,college: "University of North Texas" },
{ id: 456,college: "University of Northern Colorado" },
{ id: 457,college: "University of Notre Dame" },
{ id: 458,college: "University of Oklahoma" },
{ id: 459,college: "University of Oregon" },
{ id: 460,college: "University of Pennsylvania" },
{ id: 461,college: "University of Pittsburgh" },
{ id: 462,college: "University of Portland" },
{ id: 463,college: "University of Puget Sound" },
{ id: 464,college: "University of Rhode Island" },
{ id: 465,college: "University of Richmond" },
{ id: 466,college: "University of Rochester" },
{ id: 467,college: "University of San Diego" },
{ id: 468,college: "University of San Francisco" },
{ id: 469,college: "University of Scranton" },
{ id: 470,college: "University of South Alabama" },
{ id: 471,college: "University of South Carolina" },
{ id: 472,college: "University of South Carolina - Aiken" },
{ id: 473,college: "University of South Carolina - Upstate" },
{ id: 474,college: "University of South Dakota" },
{ id: 475,college: "University of South Florida" },
{ id: 476,college: "University of Southern California" },
{ id: 477,college: "University of Southern Mississippi" },
{ id: 478,college: "University of St. Thomas" },
{ id: 479,college: "University of Tennessee" },
{ id: 480,college: "University of Texas - Arlington" },
{ id: 481,college: "University of Texas - Austin" },
{ id: 482,college: "University of Texas - Dallas" },
{ id: 483,college: "University of Texas - El Paso" },
{ id: 484,college: "University of Texas - San Antonio" },
{ id: 485,college: "University of Toledo" },
{ id: 486,college: "University of Tulsa" },
{ id: 487,college: "University of Utah" },
{ id: 488,college: "University of Vermont" },
{ id: 489,college: "University of Virginia" },
{ id: 490,college: "University of Washington" },
{ id: 491,college: "University of West Florida" },
{ id: 492,college: "University of West Georgia" },
{ id: 493,college: "University of Wisconsin - Madison" },
{ id: 494,college: "University of Wisconsin - Milwaukee" },
{ id: 495,college: "University of Wyoming" },
{ id: 496,college: "University of the Cumberlands" },
{ id: 497,college: "University of the Ozarks" },
{ id: 498,college: "University of the Pacific" },
{ id: 499,college: "Ursinus College" },
{ id: 500,college: "Utah State University" },
{ id: 501,college: "Valdosta State University" },
{ id: 502,college: "Valparaiso University" },
{ id: 503,college: "Vanderbilt University" },
{ id: 504,college: "Vassar College" },
{ id: 505,college: "Vaughn College of Aeronautics and Technology" },
{ id: 506,college: "Villanova University" },
{ id: 507,college: "Virginia Commonwealth University" },
{ id: 508,college: "Virginia Military Institute" },
{ id: 509,college: "Virginia Tech" },
{ id: 510,college: "Wabash College" },
{ id: 511,college: "Wake Forest University" },
{ id: 512,college: "Warner Pacific College" },
{ id: 513,college: "Washington College" },
{ id: 514,college: "Washington State University" },
{ id: 515,college: "Washington University in St. Louis" },
{ id: 516,college: "Washington and Jefferson College" },
{ id: 517,college: "Washington and Lee University" },
{ id: 518,college: "Wayne State University" },
{ id: 519,college: "Wellesley College" },
{ id: 520,college: "Wesleyan University" },
{ id: 521,college: "West Virginia University" },
{ id: 522,college: "Western Michigan University" },
{ id: 523,college: "Westminster College" },
{ id: 524,college: "Westmont College" },
{ id: 525,college: "Wheaton College" },
{ id: 526,college: "Whitman College" },
{ id: 527,college: "Whitworth University" },
{ id: 528,college: "Wichita State University" },
{ id: 529,college: "Widener University" },
{ id: 530,college: "Willamette University" },
{ id: 531,college: "Williams College" },
{ id: 532,college: "Wilmington University" },
{ id: 533,college: "Wofford College" },
{ id: 534,college: "Worcester Polytechnic Institute" },
{ id: 535,college: "Wright State University" },
{ id: 536,college: "Xavier University" },
{ id: 537,college: "Xavier University of Louisiana" },
{ id: 538,college: "Yale University" },
{ id: 539,college: "Yeshiva University" }
];

export default colleges;